### ISSUE TITLE
Throw error when layer is not added to map

### ISSUE THREAD

**Issue by baffioso** [Septima/qgis-qlrbrowser#60] opened 2016-09-15 08:36 UTC
Our users doesn't always have access to our PostgreSQL db due to connection problems at the moment. When they try to add a "dead" layer from QLR-browser it appears in the Layers Panel (without geometry signature), but nothing is added to the map. Would be handy for the users if get an error message, when this happens.

**Comment by Frederikssund** [comment] 2016-09-15 09:56
@baffioso , what happens if you add the qlr file manually (Menu "Layer" -> "Add from layer definition file") and you have the same situation with the database ?

**Comment by baffioso** [comment] 2016-09-15 13:51
@Frederikssund It's the same. No error when adding a layer

**Comment by Frederikssund** [comment] 2016-09-16 08:30
@baffioso - It probably means the problem isn't solveable by changing the python code for the plugin. It's a bug in the main QGIS code. I'll make a test in my own environment and report it as a bug in QGIS.

**Comment by baffioso** [comment] 2016-09-16 09:15
Thanks

**Comment by Frederikssund** [comment] 2016-09-16 09:22
@baffioso - I've just made a check by creating a qlr file that refer to a SQL server based layer. After creating the qlr file, I maually edited the qlr-file and changed the definition of the databasename to a non existing database (emulating a non-responsive database ) and tried to reopen the edited qlr file in Qgis. The result was:
1. A new layer in the layer selector with the right name, but no thematic information 
2. No new data on the map (Doh!!)
3. Most important: _No_ error from Qgis.

I'll report this as a bug ASAP to the Qgis bug list.

**Comment by MieWinstrup** [comment] 2016-09-16 09:25
@Frederikssund thanks for reporting!

**Comment by Frederikssund** [comment] 2016-09-17 08:13
Error reported on QGIS buglist as : [http://hub.qgis.org/issues/15574](http://hub.qgis.org/issues/15574)

**Comment by MieWinstrup** [comment] 2016-09-28 07:52
I will close this issue for now since it's a bug in QGIS-main-code. If this still is a problem when the bug is fixed in QGIS, this issue should be reopened.

**Closed as completed by MieWinstrup** 2016-09-28 07:52 UTC
