### ISSUE TITLE
Can't read QLR-files with groups

### ISSUE THREAD

**Issue by Geodataodense** [Septima/qgis-qlrbrowser#82] opened 2021-03-26 13:39 UTC
QLR-Browser fails when loading qrl-files.
qlr-files works fine when read manual from layers menu.
Works fine when read through the QLR-browser in QGIS-version 3.16

**Comment by Geodataodense** [comment] 2021-04-08 07:59
The problem seems to occur only when qlr-files are pointing at databasesource from a database.
qlr-example attashed
[Fredning (DAI).zip](https://github.com/Septima/qgis-qlrbrowser/files/6277023/Fredning.DAI.zip)

**Comment by AsgerPetersen** [comment] 2021-04-08 08:14
Hi @Geodataodense 

Could you please clarify what it takes to make the QLR Browser fail? Do we have to use a specific QGIS version (you say that it works in 3.16)?

Thank you for reporting this issue.

**Comment by Geodataodense** [comment] 2021-04-08 09:16
I am using the latest version of QGIS an plugin.
The QLR-browser fails to load the qlr-file in QGIS 3.18.1 only.
It works fine when read through the QLR-browser in QGIS-version 3.16

We are happy users an depend on the plugin in Odense. 
The QLR-browser makes it easy for the users to access all kinds off datasources. :-) 

If it is a big issue let us now - perhaps  we can find a way to support you

Regards Peter Jørgensen

**Comment by MieWinstrup** [comment] 2021-04-12 06:34
Hi. 
Yes, thanks for reporting the issue. 

I have tried to reproduce the problem by:

1. In QGIS 3.16 saving a qlr-file, pointing to a vector dataset in a Postgres-database, to the folder of the qlr-browser 
2. Adding the qlr-file in QGIS 3.16 - works fine
3. Adding the qlr-file in QGIS 3.18 - works fine

We need some more details about the problem that you experience.

In QGIS 3.18 - can you add the qlr-file from the normal browser in QGIS?
![image](https://user-images.githubusercontent.com/16276034/114350479-80d13e00-9b69-11eb-971a-8d6c3b05d538.png)

What happen when you add the qlr-file from the Qlr-browser in QGIS 3.18 - do you get an error message? Or something else?

**Comment by Geodataodense** [comment] 2021-04-12 07:02
Hello Mie :-) 
Did you succeed using attached - the qlr-file connecting to Geo Fyn.
The error messages is.
2021-04-12T08:54:45     WARNING    HTTP fetch ../../Direkte adgang/Fmk mislykkedes med fejl: Protokollen "" er ukendt
Give me a call if you cannot reproduce the issue

**Comment by MieWinstrup** [comment] 2021-04-12 07:08
Hi Peter,
Unfortunately, I can't test it with the attached qlr-file:

![image](https://user-images.githubusercontent.com/16276034/114354458-9006ba80-9b6e-11eb-8049-1d89c8dffabc.png)

**Comment by Geodataodense** [comment] 2021-04-12 07:12
Perhaps there is IP-validation on the database server

**Comment by MieWinstrup** [comment] 2021-04-12 09:03
The problem with loading a qlr-file from Qlr-browser in QGIS 3.18 happens when the layers in a qlr-file is a ordered in a group of layers. 

Since the problem occurs when datasources in a group are from database or webservices (WMS, WFS), it seems like it is the group that makes the problem, and that is it not related to the kind of data (database, webservice etc.).

**Comment by Geodataodense** [comment] 2021-04-20 13:34
Can you fix the group-error in the QLR-code or is it a core-issue. 
I have just installed QGIS 3.18.2-1 and the QLR-browser doesn't work properly here either

**Comment by reginaldc** [comment] 2021-04-21 06:15
I'm using Qgis 3.16.5 and I am having the same issues with qlrfiles derived from grouped layers. They used to show up correctly but it looks like something has changed and they don't show up anymore. There is also a lot of commented code in the qlrfiles. I don't remember that it was there before.

**Comment by MieWinstrup** [comment] 2021-04-29 10:28
We have estimated that the bugfix is something between 2 and 10 hours including packaging the plugin as a new version and upload to plugin repository. If anyone want to fund - or co-fund - the bugfix, please let me know (mie@septima.dk)

**Comment by bvthomsen** [comment] 2021-12-08 09:32
Solved if pull request https://github.com/Septima/qgis-qlrbrowser/pull/84#issue-1074183762 is implemented. in master

**Comment by MieWinstrup** [comment] 2021-12-31 14:34
[Fixed in version 3.0.0. ](https://github.com/Septima/qgis-qlrbrowser/releases/tag/v.3.0.0)

**Closed as completed by MieWinstrup** 2021-12-31 14:34 UTC
